spring:
  data:
    mongodb:
      #uri: mongodb+srv://admin:admin@demo.uskpz.mongodb.net/hkjc?authSource=admin
      uri: mongodb+srv://admin:admin@atlassearch.uskpz.mongodb.net/hkjc?authSource=admin
settings:
  dbName: test-transaction
  collectionName: account
  noOfThread: 30
  noOfAccount: 100000
  initialBalance: 100
  noOfTransfer: 100000
  transferAmount: 10

  corePoolsize: 20
  maxPoolSize: 50
  queueSize: 10