spring:
  data:
    mongodb:
      #uri: mongodb+srv://admin:admin@demo.uskpz.mongodb.net/hkjc?authSource=admin
      uri: mongodb+srv://admin:admin@atlassearch.uskpz.mongodb.net/hkjc?authSource=admin
settings:
  dbName: test-transaction
  collectionName: account
  noOfThread: 20
  noOfAccount: 200000
  initialBalance: 100
  noOfTransfer: 10
  transferAmount: 50

  corePoolsize: 10
  maxPoolSize: 30
  queueSize: 10