spring:
  data:
    mongodb:
      #uri: mongodb+srv://admin:admin@demo.uskpz.mongodb.net/test?authSource=admin
      #uri: mongodb+srv://admin:admin@atlassearch.uskpz.mongodb.net/test?authSource=admin
      uri: mongodb+srv://admin:admin@shard-demo.uskpz.mongodb.net/test?authSource=admin
settings:
  dbName: test-transaction
  collectionName: account
  transferLogCollectionName: transferLog

  noOfThread: 30 # No. of workers to process generated transaction, Higher value will introduce more transaction & threads, Lower value will introduce larger batch size
  noOfAccount: 1000000 # Total no. of Accounts, fewer accounts will have greater chance to introduce write conflict (transaction retry)
  initialBalance: 100 # Initial balance of each accounts
  noOfTransfer: 1000 # How many transfer occurs simultaneously, Higher value will introduce more transaction/greater batch size
  transferAmount: 1 # [Only use for demonstrate write conflit] How many amount will be deduct from a random account and thus how many random transferee accounts balance will be added by $1 each, greater number will introduce greater chance of write conflict (transaction retry)

  #App thread pool setting
  corePoolsize: 10 
  maxPoolSize: 50
  queueSize: 100000