spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@atlassearch.uskpz.mongodb.net/hkjc?authSource=admin
settings:
  dbName: test-transaction
  collectionName: account
  noOfAccount: 100
  initialBalance: 100
  noOfTransfer: 10
  transferAmount: 50